---
- name: nginx code signing key in place
  ansible.builtin.get_url:
    url: https://nginx.org/keys/nginx_signing.key
    dest: /etc/apt/trusted.gpg.d/nginx.asc
- name: nginx apt repository registered
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/nginx.asc] http://nginx.org/packages/ubuntu {{ansible_distribution_release}} nginx"
    state: present
- name: nginx installed
  ansible.builtin.apt:
    name: nginx={{u22_nginx_version}}
    state: present
- name: nginx default site content removed
  ansible.builtin.file:
    path: /var/www/default
    state: absent
- name: nginx default site content replaced
  ansible.builtin.copy:
    src: default
    dest: /var/www
    owner: www-data
    group: www-data
    mode: "0664"
- name: nginx default site config in place
  notify: restart nginx
  ansible.builtin.template:
    src: default
    dest: /etc/nginx/sites-available
    owner: root
    group: root
    mode: "0644"
- name: nginx sites-enabled directory removed
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled
    state: absent
- name: nginx sites-enabled empty directory replaced
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled
    state: directory
- name: nginx default site enabled
  notify: restart nginx
  ansible.builtin.file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
- name: nginx main config in place
  notify: restart nginx
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx
    owner: root
    group: root
    mode: "0644"
- name: php-fpm installed
  ansible.builtin.apt:
    name:
      - php{{u22_php_version}}-fpm
      - php{{u22_php_version}}-cli
    state: latest
- name: php extensions installed
  ansible.builtin.apt:
    name:
      - php{{u22_php_version}}-bcmath
      - php{{u22_php_version}}-curl
      - php{{u22_php_version}}-gd
      - php{{u22_php_version}}-intl
      - php{{u22_php_version}}-mbstring
      - php{{u22_php_version}}-soap
      - php{{u22_php_version}}-xml
    state: latest
- name: php-fpm configuration in place
  notify: restart php-fpm
  ansible.builtin.template:
    src: php.ini
    dest: /etc/php/{{u22_php_version}}/fpm
    owner: root
    group: root
    mode: "0644"
- name: php-cli configuration in place
  ansible.builtin.template:
    src: php.ini
    dest: /etc/php/{{u22_php_version}}/cli
    owner: root
    group: root
    mode: "0644"
- name: composer downloaded as system binary
  ansible.builtin.get_url:
    url: https://getcomposer.org/download/{{u22_composer_version}}/composer.phar
    checksum: sha256:https://getcomposer.org/download/{{u22_composer_version}}/composer.phar.sha256sum
    dest: /usr/local/bin/composer
    owner: root
    group: root
    mode: "0755"
- name: nginx service enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
